# Generated by Django 4.0.3 on 2022-03-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='exert',
            field=models.TextField(blank=True, null=True),
        ),
    ]
