# Generated by Django 4.0.3 on 2022-03-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_exert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='exert',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
