# Generated by Django 4.0.3 on 2022-04-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='twitter_handle',
            field=models.CharField(default='@iyosayi18', max_length=50),
        ),
    ]
