# Generated by Django 4.0.3 on 2022-04-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_letter_user',
            options={'verbose_name': 'News Letter User', 'verbose_name_plural': 'News Letter Users'},
        ),
    ]
